services:
  postgres:
    image: 'postgres:${POSTGRES_IMAGE_TAG}'
    restart: '${RESTART_POLICY}'
    security_opt:
      - 'no-new-privileges:true'
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - '/data/coolify/applications/okkkg0g/postgres_data:/var/lib/postgresql/data'
    environment:
      - '${TZ}'
      - '${POSTGRES_USER}'
      - '${POSTGRES_PASSWORD}'
      - '${POSTGRES_DB}'
    networks:
      rgo0g8w: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.319
      - coolify.applicationId=32
      - coolify.type=application
      - coolify.name=postgres-rgo0g8w-231151856316
      - coolify.pullRequestId=0
    container_name: postgres-rgo0g8w-231151856316
  mattermost:
    depends_on:
      - postgres
    image: 'mattermost/${MATTERMOST_IMAGE}:${MATTERMOST_IMAGE_TAG}'
    restart: '${RESTART_POLICY}'
    security_opt:
      - 'no-new-privileges:true'
    pids_limit: 200
    read_only: '${MATTERMOST_CONTAINER_READONLY}'
    tmpfs:
      - /tmp
    volumes:
      - '/data/coolify/applications/okkkg0g/config:/mattermost/config:rw'
      - '/data/coolify/applications/okkkg0g/data:/mattermost/data:rw'
      - '/data/coolify/applications/okkkg0g/logs:/mattermost/logs:rw'
      - '/data/coolify/applications/okkkg0g/plugins:/mattermost/plugins:rw'
      - '/data/coolify/applications/okkkg0g/client/plugins:/mattermost/client/plugins:rw'
      - '/data/coolify/applications/okkkg0g/bleve-indexes:/mattermost/bleve-indexes:rw'
    environment:
      - '${TZ}'
      - '${MM_SQLSETTINGS_DRIVERNAME}'
      - '${MM_SQLSETTINGS_DATASOURCE}'
      - '${MM_BLEVESETTINGS_INDEXDIR}'
      - '${MM_SERVICESETTINGS_SITEURL}'
    networks:
      rgo0g8w: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.319
      - coolify.applicationId=32
      - coolify.type=application
      - coolify.name=mattermost-rgo0g8w-231151874524
      - coolify.pullRequestId=0
    container_name: mattermost-rgo0g8w-231151874524
networks:
  rgo0g8w:
    name: rgo0g8w
    external: true
configs: {  }
secrets: {  }
